// ============ CATALOGS.JS - ВСЕ СПРАВОЧНЫЕ ДАННЫЕ ==========
// Единый источник правды для метрик, синонимов и справочников

// ============ 1. ПОЛНЫЙ СПРАВОЧНИК МЕТРИК ==========
const METRICS_CATALOG = {
  // P&L
  revenue: { tags: ['Revenues', 'RevenueFromContractWithCustomerExcludingAssessedTax', 'RevenueFromContractWithCustomerIncludingAssessedTax', 'RevenuesNetOfInterestExpense', 'RegulatedAndUnregulatedOperatingRevenue', 'RegulatedOperatingRevenue', 'InvestmentBankingRevenue', 'GrossInvestmentIncomeOperating'], compute: ['InterestIncomeExpenseNet', 'NoninterestIncome'], operation: 'sum', category: 'P&L', ttm: 'sum', ru: 'Выручка' },
  cogs: { tags: ['CostOfGoodsAndServicesSold', 'CostOfRevenue', 'CostOfSales', 'CostsAndExpenses', 'CostOfServices'], category: 'P&L', ttm: 'sum', ru: 'Себестоимость' },
  grossprofit: { tags: ['GrossProfit'], category: 'P&L', ttm: 'sum', ru: 'Валовая прибыль' },
  rd: { tags: ['ResearchAndDevelopmentExpense', 'ResearchAndDevelopmentExpenseExcludingAcquiredInProcessResearchAndDevelopment'], category: 'P&L', ttm: 'sum', ru: 'R&D расходы' },
  sga: { tags: ['SellingGeneralAndAdministrativeExpense'], category: 'P&L', ttm: 'sum', ru: 'SG&A расходы' },
  operatingexpenses: { tags: ['OperatingExpenses'], category: 'P&L', ttm: 'sum', ru: 'Операционные расходы' },
  operatingincome: { tags: ['OperatingIncomeLoss'], category: 'P&L', ttm: 'sum', ru: 'Операционная прибыль' },
  interestincome: { tags: ['InvestmentIncomeInterest', 'InterestIncome'], category: 'P&L', ttm: 'sum', ru: 'Процентный доход' },
  interestexpense: { tags: ['InterestExpense'], category: 'P&L', ttm: 'sum', ru: 'Процентные расходы' },
  otherincome: { tags: ['OtherIncome', 'OtherNonoperatingIncomeExpense'], category: 'P&L', ttm: 'sum', ru: 'Прочие доходы/расходы' },
  incomebeforetax: { tags: ['IncomeLossFromContinuingOperationsBeforeIncomeTaxes', 'IncomeBeforeTax'], category: 'P&L', ttm: 'sum', ru: 'Прибыль до налога' },
  taxexpense: { tags: ['IncomeTaxExpenseBenefit'], category: 'P&L', ttm: 'sum', ru: 'Налог на прибыль' },
  netincome: { tags: ['NetIncomeLoss', 'ProfitLoss', 'NetIncomeLossAvailableToCommonStockholdersBasic', 'ComprehensiveIncomeNetOfTax'], category: 'P&L', ttm: 'sum', ru: 'Чистая прибыль' },
  aaa: { tags: ['ExciseAndSalesTaxes'], category: 'P&L', ttm: 'sum', ru: 'Акцизы' },
  
  // Balance Sheet - Assets
  totalassets: { tags: ['Assets'], category: 'Balance', ttm: 'last', ru: 'ВСЕГО АКТИВЫ' },
  currentassets: { tags: ['AssetsCurrent'], category: 'Balance', ttm: 'last', ru: 'Оборотные активы' },
  cashandequivalents: { tags: ['CashAndCashEquivalentsAtCarryingValue', 'CashAndCashEquivalentsAtFairValue', 'CashCashEquivalentsAndShortTermInvestments', 'CashAndDueFromBanks'], category: 'Balance', ttm: 'last', ru: 'Деньги и эквиваленты' },
  shortterminvestments: { tags: ['MarketableSecuritiesCurrent'], category: 'Balance', ttm: 'last', ru: 'Краткосрочные инвестиции' },
  accountsreceivable: { tags: ['AccountsReceivableNetCurrent', 'ReceivablesNetCurrent'], category: 'Balance', ttm: 'last', ru: 'Дебиторская задолженность' },
  inventory: { tags: ['InventoryNet', 'InventoryFinishedGoods', 'InventoryRawMaterialsAndSupplies', 'InventoryWorkInProcessAndFinishedGoods'], category: 'Balance', ttm: 'last', ru: 'Запасы' },
  prepaidexpenses: { tags: ['PrepaidExpenseCurrent', 'OtherAssetsCurrent'], category: 'Balance', ttm: 'last', ru: 'Предоплаченные расходы' },
  othercurrentassets: { tags: ['OtherAssetsCurrent'], category: 'Balance', ttm: 'last', ru: 'Прочие оборотные активы' },
  noncurrentassets: { tags: ['AssetsNoncurrent'], category: 'Balance', ttm: 'last', ru: 'Внеоборотные активы' },
  ppe: { tags: ['PropertyPlantAndEquipmentNet', 'PropertyPlantAndEquipmentAndOperatingLeaseRightOfUseAssetAfterAccumulatedDepreciationAndAmortization', 'PropertyPlantAndEquipmentAndFinanceLeaseRightOfUseAssetAfterAccumulatedDepreciationAndAmortization'], category: 'Balance', ttm: 'last', ru: 'Основные средства' },
  intangibleassets: { tags: ['IntangibleAssetsNetExcludingGoodwill', 'IntangibleAssetsNetIncludingGoodwill'], category: 'Balance', ttm: 'last', ru: 'Нематериальные активы' },
  goodwill: { tags: ['Goodwill'], category: 'Balance', ttm: 'last', ru: 'Гудвилл' },
  longterminvestments: { tags: ['LongTermInvestments', 'MarketableSecuritiesNoncurrent'], category: 'Balance', ttm: 'last', ru: 'Долгосрочные инвестиции' },
  accumulateddepreciation: { tags: ['AccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment'], category: 'Balance', ttm: 'last', ru: 'Накопленная амортизация' },
  deferredtaxassets: { tags: ['DeferredTaxAssetsNet'], category: 'Balance', ttm: 'last', ru: 'Отложенные налоговые активы' },
  othernoncurrentassets: { tags: ['OtherAssetsNoncurrent'], category: 'Balance', ttm: 'last', ru: 'Прочие внеоборотные активы' },

  // Balance Sheet - Liabilities
  totalliabilities: { tags: ['Liabilities'], category: 'Balance', ttm: 'last', ru: 'ВСЕГО ОБЯЗАТЕЛЬСТВА' },
  totalcurrentliabilities: { tags: ['LiabilitiesCurrent'], category: 'Balance', ttm: 'last', ru: 'Итого краткосрочные обязательства' },
  accountspayable: { tags: ['AccountsPayableCurrent'], category: 'Balance', ttm: 'last', ru: 'Кредиторская задолженность' },
  accruedliabilities: { tags: ['AccruedLiabilitiesCurrent'], category: 'Balance', ttm: 'last', ru: 'Начисленные обязательства' },
  apal: { tags: ['AccountsPayableAndAccruedLiabilitiesCurrent'], category: 'Balance', ttm: 'last', ru: 'Кредиторская задолженность и начисленные обязательства' },
  shorttermdebt: { tags: ['ShortTermBorrowings', 'LongTermDebtCurrent', 'CurrentPortionOfLongTermDebt', 'ShortTermBankBorrowings'], category: 'Balance', ttm: 'last', ru: 'Краткосрочный долг' },
  deferredrevenue: { tags: ['DeferredRevenueCurrent', 'ContractWithCustomerLiabilityCurrent'], category: 'Balance', ttm: 'last', ru: 'Деферредный доход' },
  othercurrentliabilities: { tags: ['OtherLiabilitiesCurrent'], category: 'Balance', ttm: 'last', ru: 'Прочие краткосрочные обязательства' },
  totalnoncurrentliabilities: { tags: ['LiabilitiesNoncurrent'], category: 'Balance', ttm: 'last', ru: 'Итого долгосрочные обязательства' },
  longtermdebt: { tags: ['LongTermDebt', 'LongTermDebtNoncurrent', 'LongTermDebtAndCapitalLeaseObligations'], category: 'Balance', ttm: 'last', ru: 'Долгосрочный долг' },
  deferredtaxliabilities: { tags: ['DeferredTaxLiabilitiesNet'], category: 'Balance', ttm: 'last', ru: 'Отложенные налоговые обязательства' },
  deferredrevenuenoncurrent: { tags: ['DeferredRevenueNoncurrent', 'ContractWithCustomerLiabilityNoncurrent'], category: 'Balance', ttm: 'last', ru: 'Деферредный доход долгосрочный' },
  pensionliabilities: { tags: ['PensionAndOtherPostretirementDefinedBenefitPlansLiabilitiesNoncurrent'], category: 'Balance', ttm: 'last', ru: 'Пенсионные обязательства' },
  othernoncurrentliabilities: { tags: ['OtherLiabilitiesNoncurrent'], category: 'Balance', ttm: 'last', ru: 'Прочие долгосрочные обязательства' },

  // Equity
  preferredstock: { tags: ['PreferredStockValue', 'PreferredStockSharesOutstanding'], category: 'Equity', ttm: 'last', ru: 'Привилегированные акции' },
  commonstock: { tags: ['CommonStockValue', 'CommonStocksIncludingAdditionalPaidInCapital'], category: 'Equity', ttm: 'last', ru: 'Обыкновенные акции' },
  additionalpaidincapital: { tags: ['AdditionalPaidInCapital'], category: 'Equity', ttm: 'last', ru: 'Дополнительный капитал' },
  retainedearnings: { tags: ['RetainedEarningsAccumulatedDeficit', 'RetainedEarnings'], category: 'Equity', ttm: 'last', ru: 'Нераспределённая прибыль' },
  accumulatedothercomprehensiveincome: { tags: ['AccumulatedOtherComprehensiveIncomeLossNetOfTax'], category: 'Equity', ttm: 'last', ru: 'Прочий совокупный доход' },
  treasurystock: { tags: ['TreasuryStockValue', 'TreasuryStockCommon'], category: 'Equity', ttm: 'last', ru: 'Казначейские акции' },
  totalequity: { tags: ['StockholdersEquity', 'PartnersCapital', 'MembersEquity', 'Equity'], category: 'Equity', ttm: 'last', ru: 'ВСЕГО КАПИТАЛ' },

  // Cash Flow
  ocf: { tags: ['NetCashProvidedByUsedInOperatingActivities', 'NetCashProvidedByUsedInOperatingActivitiesContinuingOperations', 'CashFlowsFromUsedInOperatingActivities'], category: 'CashFlow', ttm: 'sum', ru: 'OCF' },
  icf: { tags: ['NetCashProvidedByUsedInInvestingActivities', 'CashFlowsFromUsedInInvestingActivities'], category: 'CashFlow', ttm: 'sum', ru: 'ICF' },
  fcf: { tags: ['NetCashProvidedByUsedInFinancingActivities', 'CashFlowsFromUsedInFinancingActivities'], category: 'CashFlow', ttm: 'sum', ru: 'FCF' },
  netchangeincash: { tags: ['CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsPeriodIncreaseDecreaseIncludingExchangeRateEffect'], compute: ['CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsPeriodIncreaseDecreaseExcludingExchangeRateEffect', 'EffectOfExchangeRateOnCashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents', 'IncreaseDecreaseInCashAndCashEquivalentsBeforeEffectOfExchangeRateChanges', 'EffectOfExchangeRateChangesOnCashAndCashEquivalents'], operation: 'sum', category: 'CashFlow', ttm: 'sum', ru: 'Чистое изменение денег' },
  da: { tags: ['DepreciationDepletionAndAmortization', 'Depreciation', 'DepreciationAndAmortization', 'DepreciationAmortizationAndAccretionNet', 'DepreciationAndAmortizationExcludingDebtIssuanceCosts', 'AmortizationOfIntangibleAssets', 'DepreciationAmortizationDecommissioning'], category: 'CashFlow', ttm: 'sum', ru: 'Амортизация и износ' },
  netincomecf: { tags: ['NetIncomeLoss'], category: 'CashFlow', ttm: 'sum', ru: 'Чистая прибыль (для CF)' },
  stockbasedcompensation: { tags: ['ShareBasedCompensation'], category: 'CashFlow', ttm: 'sum', ru: 'Вознаграждение акциями' },
  deferredtax: { tags: ['DeferredIncomeTaxExpenseBenefit'], category: 'CashFlow', ttm: 'sum', ru: 'Отложенные налоги' },
  workingcapitalchanges: { tags: ['IncreaseDecreaseInOperatingCapital'], category: 'CashFlow', ttm: 'sum', ru: 'Изменение оборотного капитала' },
  accountsreceivablechange: { tags: ['IncreaseDecreaseInAccountsReceivable'], category: 'CashFlow', ttm: 'sum', ru: 'Изменение дебиторки' },
  inventorychange: { tags: ['IncreaseDecreaseInInventories'], category: 'CashFlow', ttm: 'sum', ru: 'Изменение запасов' },
  accountspayablechange: { tags: ['IncreaseDecreaseInAccountsPayable'], category: 'CashFlow', ttm: 'sum', ru: 'Изменение кредиторки' },
  otheroperatingactivities: { tags: ['OtherOperatingActivities'], category: 'CashFlow', ttm: 'sum', ru: 'Прочие операционные' },
  capex: { tags: ['PaymentsToAcquirePropertyPlantAndEquipment', 'CapitalExpendituresIncurredButNotYetPaid', 'PurchaseOfPropertyPlantAndEquipment'], category: 'CashFlow', ttm: 'sum', ru: 'Капекс' },
  acquisitions: { tags: ['PaymentsToAcquireBusinessesNetOfCashAcquired', 'AcquisitionsNetOfCashAcquired'], category: 'CashFlow', ttm: 'sum', ru: 'Приобретения' },
  purchaseofinvestments: { tags: ['PaymentsToAcquireInvestments'], category: 'CashFlow', ttm: 'sum', ru: 'Покупка инвестиций' },
  saleofinvestments: { tags: ['ProceedsFromSaleAndMaturityOfInvestments'], category: 'CashFlow', ttm: 'sum', ru: 'Продажа инвестиций' },
  otherinvestingactivities: { tags: ['OtherInvestingActivities'], category: 'CashFlow', ttm: 'sum', ru: 'Прочие инвестиционные' },
  debtissuance: { tags: ['ProceedsFromIssuanceOfLongTermDebt', 'ProceedsFromBorrowings'], category: 'CashFlow', ttm: 'sum', ru: 'Выпуск долга' },
  debtrepayment: { tags: ['RepaymentsOfLongTermDebt', 'RepaymentsOfDebt'], category: 'CashFlow', ttm: 'sum', ru: 'Погашение долга' },
  stockissuance: { tags: ['ProceedsFromIssuanceOfCommonStock'], category: 'CashFlow', ttm: 'sum', ru: 'Выпуск акций' },
  buybacks: { tags: ['PaymentsForRepurchaseOfCommonStock', 'PaymentsForRepurchaseOfEquity'], category: 'CashFlow', ttm: 'sum', ru: 'Выкуп акций' },
  dividendspaid: { tags: ['PaymentsOfDividends', 'PaymentsOfDividendsToNoncontrollingInterests'], category: 'CashFlow', ttm: 'sum', ru: 'Дивиденды' },
  otherfinancingactivities: { tags: ['OtherFinancingActivities'], category: 'CashFlow', ttm: 'sum', ru: 'Прочие финансовые' },
  effectofexchangerate: { tags: ['EffectOfExchangeRateOnCashAndCashEquivalents'], category: 'CashFlow', ttm: 'sum', ru: 'Влияние курсов валют' },
  beginningcash: { tags: ['CashAndCashEquivalentsAtBeginningOfPeriod'], category: 'CashFlow', ttm: 'last', ru: 'Деньги на начало' },
  endingcash: { tags: ['CashAndCashEquivalentsAtEndOfPeriod'], category: 'CashFlow', ttm: 'last', ru: 'Деньги на конец' },

  // Per Share
  sharesbasic: { tags: ['WeightedAverageNumberOfSharesOutstandingBasic'], category: 'PerShare', ttm: 'last', ru: 'Акции basic' },
  sharesdiluted: { tags: ['WeightedAverageNumberOfDilutedSharesOutstanding'], category: 'PerShare', ttm: 'last', ru: 'Акции diluted' },
  sharesoutstanding: { tags: ['CommonStockSharesOutstanding', 'EntityCommonStockSharesOutstanding'], category: 'PerShare', ttm: 'last', ru: 'Акции в обращении' },
  sharesissued: { tags: ['CommonStockSharesIssued'], category: 'PerShare', ttm: 'last', ru: 'Выпущенные акции' },
  epsbasic: { tags: ['EarningsPerShareBasic'], category: 'PerShare', ttm: 'sum', ru: 'EPS basic' },
  epsdiluted: { tags: ['EarningsPerShareDiluted'], category: 'PerShare', ttm: 'sum', ru: 'EPS diluted' },
  dividendspershare: { tags: ['CommonStockDividendsPerShareDeclared', 'DividendsPerShare'], category: 'PerShare', ttm: 'sum', ru: 'DPS' }
};

// ============ 2. ЕДИНЫЙ СЛОВАРЬ СИНОНИМОВ ==========
// Объединяет RU_ALIASES и все синонимы из GAS METRIC_SYNONYMS
const METRIC_ALIASES = {
  // ===== Русские (из RU_ALIASES) =====
  "выручка": "revenue",
  "себестоимость": "cogs",
  "валоваяприбыль": "grossprofit",
  "операционнаяприбыль": "operatingincome",
  "чистаяприбыль": "netincome",
  "активы": "totalassets",
  "обязательства": "totalliabilities",
  "капитал": "totalequity",
  "деньги": "cashandequivalents",
  "долг": "longtermdebt",
  "акции": "sharesoutstanding",
  "ocf": "ocf",
  "fcf": "fcf",
  "капекс": "capex",
  "амортизация": "da",
  
  // ===== P&L синонимы =====
  "revenue": "revenue",
  "sales": "revenue",
  "продажи": "revenue",
  "оборот": "revenue",
  "total revenue": "revenue",
  "совокупная выручка": "revenue",
  "top line": "revenue",
  "доходы": "revenue",
  "income": "revenue",
  "выручка от реализации": "revenue",
  "net sales": "revenue",
  "чистая выручка": "revenue",
  
  "aaa": "aaa",
  
  "cogs": "cogs",
  "cost of sales": "cogs",
  "cost of goods sold": "cogs",
  "cost of revenue": "cogs",
  "прямые затраты": "cogs",
  "себестоимость продаж": "cogs",
  "cost of services": "cogs",
  "стоимость услуг": "cogs",
  "trc": "cogs",
  "cost of products": "cogs",
  "себестоимость продуктов": "cogs",
  
  "grossprofit": "grossprofit",
  "gross profit": "grossprofit",
  "gross margin": "grossprofit",
  "gross profit margin": "grossprofit",
  "gp": "grossprofit",
  "валовая маржа": "grossprofit",
  "маржинальность": "grossprofit",
  "gross income": "grossprofit",
  "gross profit before tax": "grossprofit",
  
  "rd": "rd",
  "r&d": "rd",
  "research and development": "rd",
  "научка": "rd",
  "разработки": "rd",
  "ниокр": "rd",
  "research & development": "rd",
  "rd expenses": "rd",
  "затраты на исследования": "rd",
  "развитие технологий": "rd",
  "инновационные расходы": "rd",
  "development costs": "rd",
  
  "sga": "sga",
  "sg&a": "sga",
  "selling general administrative": "sga",
  "коммерческие и управленческие": "sga",
  "операционные расходы": "sga",
  "админрасходы": "sga",
  "коммерческие расходы": "sga",
  "selling expenses": "sga",
  "administrative expenses": "sga",
  "overhead": "sga",
  "накладные расходы": "sga",
  "общие и административные": "sga",
  
  "operatingexpenses": "operatingexpenses",
  "operating expenses": "operatingexpenses",
  "opex": "operatingexpenses",
  "op ex": "operatingexpenses",
  "эксплуатационные расходы": "operatingexpenses",
  "overhead costs": "operatingexpenses",
  "накладные расходы": "operatingexpenses",
  "операционка": "operatingexpenses",
  "operating costs": "operatingexpenses",
  "sales and admin": "operatingexpenses",
  
  "operatingincome": "operatingincome",
  "operating income": "operatingincome",
  "операционная доходность": "operatingincome",
  "ebit": "operatingincome",
  "operating profit": "operatingincome",
  "operating earnings": "operatingincome",
  "прибыль от операций": "operatingincome",
  "операционный результат": "operatingincome",
  "operating margin": "operatingincome",
  
  "interestincome": "interestincome",
  "interest income": "interestincome",
  "проценты полученные": "interestincome",
  "процентные доходы": "interestincome",
  "investment income": "interestincome",
  "доход от процентов": "interestincome",
  "interest received": "interestincome",
  "finance income": "interestincome",
  "прибыль от процентов": "interestincome",
  
  "interestexpense": "interestexpense",
  "interest expense": "interestexpense",
  "проценты уплаченные": "interestexpense",
  "процентные затраты": "interestexpense",
  "cost of debt": "interestexpense",
  "interest paid": "interestexpense",
  "финансовые расходы": "interestexpense",
  "стоимость заимствований": "interestexpense",
  "проценты по кредитам": "interestexpense",
  
  "otherincome": "otherincome",
  "other income": "otherincome",
  "другие доходы": "otherincome",
  "miscellaneous income": "otherincome",
  "non-operating income": "otherincome",
  "внереализационные доходы": "otherincome",
  "прочие поступления": "otherincome",
  "other operating income": "otherincome",
  "incidental income": "otherincome",
  
  "incomebeforetax": "incomebeforetax",
  "income before tax": "incomebeforetax",
  "pbt": "incomebeforetax",
  "profit before tax": "incomebeforetax",
  "pre-tax income": "incomebeforetax",
  "ebt": "incomebeforetax",
  "earnings before tax": "incomebeforetax",
  "доходность до налогообложения": "incomebeforetax",
  "налогооблагаемая прибыль": "incomebeforetax",
  
  "taxexpense": "taxexpense",
  "tax expense": "taxexpense",
  "income tax expense": "taxexpense",
  "налоги": "taxexpense",
  "corporate tax": "taxexpense",
  "current tax": "taxexpense",
  "deferred tax": "taxexpense",
  "налоговые расходы": "taxexpense",
  "income tax paid": "taxexpense",
  "provision for income taxes": "taxexpense",
  
  "netincome": "netincome",
  "net income": "netincome",
  "чистая прибыль после налогов": "netincome",
  "net profit": "netincome",
  "bottom line": "netincome",
  "ni": "netincome",
  "net earnings": "netincome",
  "чистая доходность": "netincome",
  "прибыль после налогообложения": "netincome",
  "profit after tax": "netincome",
  
  // ===== Balance Sheet - Assets =====
  "totalassets": "totalassets",
  "total assets": "totalassets",
  "совокупные активы": "totalassets",
  "балансовая стоимость активов": "totalassets",
  "assets total": "totalassets",
  "имущество компании": "totalassets",
  "внеоборотные + оборотные активы": "totalassets",
  "sum of assets": "totalassets",
  "asset base": "totalassets",
  
  "currentassets": "currentassets",
  "current assets": "currentassets",
  "текущие активы": "currentassets",
  "краткосрочные активы": "currentassets",
  "liquid assets": "currentassets",
  "ликвидные активы": "currentassets",
  "ca": "currentassets",
  "оборотка": "currentassets",
  "working capital assets": "currentassets",
  "текущее имущество": "currentassets",
  
  "cashandequivalents": "cashandequivalents",
  "cash and equivalents": "cashandequivalents",
  "денежные средства": "cashandequivalents",
  "кэш": "cashandequivalents",
  "cash": "cashandequivalents",
  "денежная наличность": "cashandequivalents",
  "ликвидность": "cashandequivalents",
  "cash and cash equivalents": "cashandequivalents",
  "денежный остаток": "cashandequivalents",
  "свободные деньги": "cashandequivalents",
  "наличность и эквиваленты": "cashandequivalents",
  
  "shortterminvestments": "shortterminvestments",
  "short term investments": "shortterminvestments",
  "краткосрочные вложения": "shortterminvestments",
  "marketable securities": "shortterminvestments",
  "рыночные ценные бумаги": "shortterminvestments",
  "временные инвестиции": "shortterminvestments",
  "st investments": "shortterminvestments",
  "инвестиции до года": "shortterminvestments",
  "торговый портфель": "shortterminvestments",
  
  "accountsreceivable": "accountsreceivable",
  "accounts receivable": "accountsreceivable",
  "дебиторка": "accountsreceivable",
  "ar": "accountsreceivable",
  "receivables": "accountsreceivable",
  "задолженность покупателей": "accountsreceivable",
  "долги клиентов": "accountsreceivable",
  "торговая дебиторка": "accountsreceivable",
  "счета к получению": "accountsreceivable",
  
  "inventory": "inventory",
  "запасы": "inventory",
  "товарные запасы": "inventory",
  "складские запасы": "inventory",
  "stocks": "inventory",
  "материальные запасы": "inventory",
  "остатки на складе": "inventory",
  "товарно-материальные запасы": "inventory",
  "finished goods": "inventory",
  "raw materials": "inventory",
  
  "prepaidexpenses": "prepaidexpenses",
  "prepaid expenses": "prepaidexpenses",
  "расходы будущих периодов": "prepaidexpenses",
  "авансы выданные": "prepaidexpenses",
  "prepaids": "prepaidexpenses",
  "предоплата": "prepaidexpenses",
  "оплаченные авансом расходы": "prepaidexpenses",
  "deferred expenses": "prepaidexpenses",
  "prepaid assets": "prepaidexpenses",
  
  "othercurrentassets": "othercurrentassets",
  "other current assets": "othercurrentassets",
  "прочая дебиторка": "othercurrentassets",
  "другие краткосрочные активы": "othercurrentassets",
  "прочие оборотные": "othercurrentassets",
  "miscellaneous current assets": "othercurrentassets",
  "non-trade receivables": "othercurrentassets",
  "oca": "othercurrentassets",
  
  "noncurrentassets": "noncurrentassets",
  "non current assets": "noncurrentassets",
  "долгосрочные активы": "noncurrentassets",
  "внеоборотка": "noncurrentassets",
  "fixed assets": "noncurrentassets",
  "долгосрочное имущество": "noncurrentassets",
  "non-current assets": "noncurrentassets",
  "постоянные активы": "noncurrentassets",
  "основные + нематериальные": "noncurrentassets",
  
  "ppe": "ppe",
  "pp&e": "ppe",
  "property plant equipment": "ppe",
  "внеоборотные средства": "ppe",
  "основные фонды": "ppe",
  "недвижимость завод оборудование": "ppe",
  "tangible assets": "ppe",
  "долгосрочное имущество": "ppe",
  "материальные активы": "ppe",
  
  "intangibleassets": "intangibleassets",
  "intangible assets": "intangibleassets",
  "гудвил": "intangibleassets",
  "интеллектуальная собственность": "intangibleassets",
  "патенты": "intangibleassets",
  "лицензии": "intangibleassets",
  "бренды": "intangibleassets",
  "intangibles": "intangibleassets",
  "ia": "intangibleassets",
  
  "goodwill": "goodwill",
  "гудвилл": "goodwill",
  "деловая репутация": "goodwill",
  "премия за бренд": "goodwill",
  "gw": "goodwill",
  "приобретенная репутация": "goodwill",
  "переоценка бизнеса": "goodwill",
  
  "longterminvestments": "longterminvestments",
  "long term investments": "longterminvestments",
  "долгосрочные вложения": "longterminvestments",
  "lt investments": "longterminvestments",
  "инвестиции в дочки": "longterminvestments",
  "стратегические инвестиции": "longterminvestments",
  "капитальные вложения": "longterminvestments",
  
  "accumulateddepreciation": "accumulateddepreciation",
  "accumulated depreciation": "accumulateddepreciation",
  "амортизация накопленная": "accumulateddepreciation",
  "износ основных средств": "accumulateddepreciation",
  "амортизационный фонд": "accumulateddepreciation",
  "depreciation reserve": "accumulateddepreciation",
  "накопленный износ": "accumulateddepreciation",
  
  "deferredtaxassets": "deferredtaxassets",
  "deferred tax assets": "deferredtaxassets",
  "dta": "deferredtaxassets",
  "отложенные налоги": "deferredtaxassets",
  "налоговые активы": "deferredtaxassets",
  "вычитаемые временные разницы": "deferredtaxassets",
  "налоговые вычеты будущих периодов": "deferredtaxassets",
  
  "othernoncurrentassets": "othernoncurrentassets",
  "other non current assets": "othernoncurrentassets",
  "прочие долгосрочные активы": "othernoncurrentassets",
  "onca": "othernoncurrentassets",
  "прочие внеоборотные": "othernoncurrentassets",
  "долгосрочные прочие": "othernoncurrentassets",
  "другие долгосрочные активы": "othernoncurrentassets",
  
  // ===== Balance Sheet - Liabilities =====
  "totalliabilities": "totalliabilities",
  "total liabilities": "totalliabilities",
  "совокупные обязательства": "totalliabilities",
  "пассивы": "totalliabilities",
  "total debt": "totalliabilities",
  "общий долг": "totalliabilities",
  "сумма обязательств": "totalliabilities",
  "liabilities total": "totalliabilities",
  
  "totalcurrentliabilities": "totalcurrentliabilities",
  "total current liabilities": "totalcurrentliabilities",
  "краткосрочные пассивы": "totalcurrentliabilities",
  "short term liabilities": "totalcurrentliabilities",
  "текущие долги": "totalcurrentliabilities",
  "кредиторка и долги": "totalcurrentliabilities",
  
  "accountspayable": "accountspayable",
  "accounts payable": "accountspayable",
  "кредиторка": "accountspayable",
  "ар": "accountspayable",
  "задолженность поставщикам": "accountspayable",
  "счета к оплате": "accountspayable",
  "долги перед поставщиками": "accountspayable",
  "trade payables": "accountspayable",
  
  "accruedliabilities": "accruedliabilities",
  "accrued liabilities": "accruedliabilities",
  "начисления": "accruedliabilities",
  "accrued expenses": "accruedliabilities",
  "задолженность по зарплате": "accruedliabilities",
  "обязательства по налогам": "accruedliabilities",
  "accrued payroll": "accruedliabilities",
  
  "apal": "apal",
  "accounts payable and accrued liabilities": "apal",
  "кредиторская задолженность и начисленные обязательства": "apal",
  "кредиторка и начисления": "apal",
  "краткосрочные долги": "apal",
  
  "shorttermdebt": "shorttermdebt",
  "short term debt": "shorttermdebt",
  "краткосрочные займы": "shorttermdebt",
  "st debt": "shorttermdebt",
  "текущая часть долга": "shorttermdebt",
  "short term borrowings": "shorttermdebt",
  "краткосрочные кредиты": "shorttermdebt",
  
  "deferredrevenue": "deferredrevenue",
  "deferred revenue": "deferredrevenue",
  "предоплата полученная": "deferredrevenue",
  "доходы будущих периодов": "deferredrevenue",
  "авансы полученные": "deferredrevenue",
  "deferred income": "deferredrevenue",
  "отложенная выручка": "deferredrevenue",
  "полученные авансы": "deferredrevenue",
  
  "othercurrentliabilities": "othercurrentliabilities",
  "other current liabilities": "othercurrentliabilities",
  "прочие краткосрочные пассивы": "othercurrentliabilities",
  "ocl": "othercurrentliabilities",
  "другие текущие обязательства": "othercurrentliabilities",
  "краткосрочные прочие": "othercurrentliabilities",
  
  "totalnoncurrentliabilities": "totalnoncurrentliabilities",
  "total non current liabilities": "totalnoncurrentliabilities",
  "долгосрочные пассивы": "totalnoncurrentliabilities",
  "long term liabilities": "totalnoncurrentliabilities",
  "долгосрочные долги": "totalnoncurrentliabilities",
  "сумма долгосрочных обязательств": "totalnoncurrentliabilities",
  
  "longtermdebt": "longtermdebt",
  "long term debt": "longtermdebt",
  "lt debt": "longtermdebt",
  "долгосрочные займы": "longtermdebt",
  "облигации к погашению": "longtermdebt",
  "bonds payable": "longtermdebt",
  "долгосрочные кредиты": "longtermdebt",
  "долговые обязательства": "longtermdebt",
  
  "deferredtaxliabilities": "deferredtaxliabilities",
  "deferred tax liabilities": "deferredtaxliabilities",
  "dtl": "deferredtaxliabilities",
  "отложенные налоги к уплате": "deferredtaxliabilities",
  "налоговые обязательства": "deferredtaxliabilities",
  "налогооблагаемые временные разницы": "deferredtaxliabilities",
  
  "deferredrevenuenoncurrent": "deferredrevenuenoncurrent",
  "deferred revenue non current": "deferredrevenuenoncurrent",
  "долгосрочная предоплата": "deferredrevenuenoncurrent",
  "отложенная выручка долгосрочная": "deferredrevenuenoncurrent",
  "long term deferred revenue": "deferredrevenuenoncurrent",
  
  "pensionliabilities": "pensionliabilities",
  "pension liabilities": "pensionliabilities",
  "пенсионный долг": "pensionliabilities",
  "обязательства по пенсиям": "pensionliabilities",
  "пенсионный фонд": "pensionliabilities",
  "post retirement liabilities": "pensionliabilities",
  
  "othernoncurrentliabilities": "othernoncurrentliabilities",
  "other non current liabilities": "othernoncurrentliabilities",
  "прочие долгосрочные пассивы": "othernoncurrentliabilities",
  "oncl": "othernoncurrentliabilities",
  "другие долгосрочные обязательства": "othernoncurrentliabilities",
  
  // ===== Equity =====
  "preferredstock": "preferredstock",
  "preferred stock": "preferredstock",
  "префы": "preferredstock",
  "preferred shares": "preferredstock",
  "привелигерованные акции": "preferredstock",
  "преференциальные акции": "preferredstock",
  "pref stock": "preferredstock",
  
  "commonstock": "commonstock",
  "common stock": "commonstock",
  "обычка": "commonstock",
  "common shares": "commonstock",
  "голосующие акции": "commonstock",
  "equity shares": "commonstock",
  "простые акции": "commonstock",
  "уставный капитал": "commonstock",
  
  "additionalpaidincapital": "additionalpaidincapital",
  "additional paid in capital": "additionalpaidincapital",
  "apic": "additionalpaidincapital",
  "эмиссионный доход": "additionalpaidincapital",
  "дополнительный капитал": "additionalpaidincapital",
  "paid in capital excess": "additionalpaidincapital",
  "взносы акционеров": "additionalpaidincapital",
  
  "retainedearnings": "retainedearnings",
  "retained earnings": "retainedearnings",
  "re": "retainedearnings",
  "нераспределенка": "retainedearnings",
  "накопленная прибыль": "retainedearnings",
  "прибыль накопленная": "retainedearnings",
  "нераспределенная прибыль прошлых лет": "retainedearnings",
  "нераспределенный остаток": "retainedearnings",
  
  "accumulatedothercomprehensiveincome": "accumulatedothercomprehensiveincome",
  "accumulated other comprehensive income": "accumulatedothercomprehensiveincome",
  "aoci": "accumulatedothercomprehensiveincome",
  "накопленный прочий доход": "accumulatedothercomprehensiveincome",
  "нереализованные доходы": "accumulatedothercomprehensiveincome",
  "прочий накопленный доход": "accumulatedothercomprehensiveincome",
  
  "treasurystock": "treasurystock",
  "treasury stock": "treasurystock",
  "казначейские": "treasurystock",
  "выкупленные акции": "treasurystock",
  "treasury shares": "treasurystock",
  "акции в казне": "treasurystock",
  "buyback stock": "treasurystock",
  
  "totalequity": "totalequity",
  "total equity": "totalequity",
  "совокупный капитал": "totalequity",
  "собственный капитал": "totalequity",
  "equity": "totalequity",
  "акционерный капитал": "totalequity",
  "чистые активы": "totalequity",
  "shareholders equity": "totalequity",
  "book value": "totalequity",
  "балансовая стоимость": "totalequity",
  
  // ===== Cash Flow =====
  "ocf": "ocf",
  "operating cash flow": "ocf",
  "денежный поток от операций": "ocf",
  "cfo": "ocf",
  "cash from operations": "ocf",
  "операционный cfd": "ocf",
  "операционная ликвидность": "ocf",
  
  "icf": "icf",
  "investing cash flow": "icf",
  "денежный поток от инвестиций": "icf",
  "cfi": "icf",
  "cash from investing": "icf",
  "инвестиционная деятельность": "icf",
  
  "fcf": "fcf",
  "free cash flow": "fcf",
  "свободный кэш": "fcf",
  "свободная ликвидность": "fcf",
  "cash after capex": "fcf",
  "денежный поток после капекса": "fcf",
  
  "netincomecf": "netincomecf",
  "net income cash flow": "netincomecf",
  "net income": "netincomecf",
  "ni cf": "netincomecf",
  
  "da": "da",
  "depreciation and amortization": "da",
  "d&a": "da",
  "износ": "da",
  "амортизационные отчисления": "da",
  "амортизация ос": "da",
  
  "stockbasedcompensation": "stockbasedcompensation",
  "stock based compensation": "stockbasedcompensation",
  "sbc": "stockbasedcompensation",
  "акционерное вознаграждение": "stockbasedcompensation",
  "выплаты акциями": "stockbasedcompensation",
  "опционы": "stockbasedcompensation",
  "rsu": "stockbasedcompensation",
  
  "deferredtax": "deferredtax",
  "отложенный налог": "deferredtax",
  "dta + dtl": "deferredtax",
  "deferred tax expense": "deferredtax",
  "налоговые отложенки": "deferredtax",
  
  "workingcapitalchanges": "workingcapitalchanges",
  "working capital changes": "workingcapitalchanges",
  "изменение оборотки": "workingcapitalchanges",
  "wc change": "workingcapitalchanges",
  "изменение текущих активов и пассивов": "workingcapitalchanges",
  
  "accountsreceivablechange": "accountsreceivablechange",
  "ar change": "accountsreceivablechange",
  "изменение дебиторской задолженности": "accountsreceivablechange",
  "ar": "accountsreceivablechange",
  
  "inventorychange": "inventorychange",
  "inventory change": "inventorychange",
  "изменение складских запасов": "inventorychange",
  "товарные остатки": "inventorychange",
  
  "accountspayablechange": "accountspayablechange",
  "ap change": "accountspayablechange",
  "изменение кредиторской задолженности": "accountspayablechange",
  "ap": "accountspayablechange",
  
  "otheroperatingactivities": "otheroperatingactivities",
  "other operating activities": "otheroperatingactivities",
  "прочие операционные потоки": "otheroperatingactivities",
  "другие поступления": "otheroperatingactivities",
  "miscellaneous operating": "otheroperatingactivities",
  
  "capex": "capex",
  "capital expenditures": "capex",
  "капитальные затраты": "capex",
  "покупка ос": "capex",
  "капитальные вложения": "capex",
  "инвестиции в основные средства": "capex",
  
  "acquisitions": "acquisitions",
  "покупка бизнесов": "acquisitions",
  "m&a": "acquisitions",
  "поглощения": "acquisitions",
  "приобретение компаний": "acquisitions",
  "покупка дочек": "acquisitions",
  
  "purchaseofinvestments": "purchaseofinvestments",
  "purchase of investments": "purchaseofinvestments",
  "приобретение инвестиций": "purchaseofinvestments",
  "покупка ценных бумаг": "purchaseofinvestments",
  "вложения в инвестиции": "purchaseofinvestments",
  
  "saleofinvestments": "saleofinvestments",
  "sale of investments": "saleofinvestments",
  "реализация инвестиций": "saleofinvestments",
  "продажа ценных бумаг": "saleofinvestments",
  "выбытие инвестиций": "saleofinvestments",
  
  "otherinvestingactivities": "otherinvestingactivities",
  "other investing activities": "otherinvestingactivities",
  "прочие инвестиционные потоки": "otherinvestingactivities",
  "другое по инвестициям": "otherinvestingactivities",
  
  "debtissuance": "debtissuance",
  "debt issuance": "debtissuance",
  "привлечение кредитов": "debtissuance",
  "получение займов": "debtissuance",
  "issuance of debt": "debtissuance",
  "выпуск облигаций": "debtissuance",
  
  "debtrepayment": "debtrepayment",
  "debt repayment": "debtrepayment",
  "выплата кредитов": "debtrepayment",
  "погашение займов": "debtrepayment",
  "repayment of debt": "debtrepayment",
  "возврат кредитов": "debtrepayment",
  
  "stockissuance": "stockissuance",
  "stock issuance": "stockissuance",
  "эмиссия акций": "stockissuance",
  "размещение акций": "stockissuance",
  "ipo": "stockissuance",
  "допэмиссия": "stockissuance",
  "issue of shares": "stockissuance",
  
  "buybacks": "buybacks",
  "обратный выкуп": "buybacks",
  "байбэк": "buybacks",
  "repurchase": "buybacks",
  "покупка собственных акций": "buybacks",
  
  "dividendspaid": "dividendspaid",
  "dividends paid": "dividendspaid",
  "выплаты дивидендов": "dividendspaid",
  "дивидендные выплаты": "dividendspaid",
  "cash dividends": "dividendspaid",
  "выплаченные дивиденды": "dividendspaid",
  
  "otherfinancingactivities": "otherfinancingactivities",
  "other financing activities": "otherfinancingactivities",
  "прочие финансовые потоки": "otherfinancingactivities",
  "другое по финансированию": "otherfinancingactivities",
  
  "effectofexchangerate": "effectofexchangerate",
  "effect of exchange rate": "effectofexchangerate",
  "валютная разница": "effectofexchangerate",
  "курсовые разницы": "effectofexchangerate",
  "forex effect": "effectofexchangerate",
  "влияние валюты": "effectofexchangerate",
  
  "netchangeincash": "netchangeincash",
  "net change in cash": "netchangeincash",
  "прирост денег": "netchangeincash",
  "изменение ликвидности": "netchangeincash",
  "увеличение денежных средств": "netchangeincash",
  
  "beginningcash": "beginningcash",
  "beginning cash": "beginningcash",
  "начальный остаток": "beginningcash",
  "наличность на начало": "beginningcash",
  "opening cash": "beginningcash",
  "cash at start": "beginningcash",
  
  "endingcash": "endingcash",
  "ending cash": "endingcash",
  "конечный остаток": "endingcash",
  "наличность на конец": "endingcash",
  "closing cash": "endingcash",
  "cash at end": "endingcash",
  
  // ===== Per Share =====
  "sharesbasic": "sharesbasic",
  "shares basic": "sharesbasic",
  "акции basic": "sharesbasic",
  "средневзвешенные акции basic": "sharesbasic",
  "weighted average shares basic": "sharesbasic",
  "waso": "sharesbasic",
  
  "sharesdiluted": "sharesdiluted",
  "shares diluted": "sharesdiluted",
  "акции diluted": "sharesdiluted",
  "разводненные акции": "sharesdiluted",
  "средневзвешенные акции diluted": "sharesdiluted",
  "waso diluted": "sharesdiluted",
  "fully diluted shares": "sharesdiluted",
  
  "sharesoutstanding": "sharesoutstanding",
  "shares outstanding": "sharesoutstanding",
  "акции в обращении": "sharesoutstanding",
  "акции выпущенные": "sharesoutstanding",
  "обыкновенные акции в обращении": "sharesoutstanding",
  "issued shares": "sharesoutstanding",
  "количество акций": "sharesoutstanding",
  
  "sharesissued": "sharesissued",
  "shares issued": "sharesissued",
  "выпущенные акции": "sharesissued",
  "размещенные акции": "sharesissued",
  "объявленные акции": "sharesissued",
  "total issued shares": "sharesissued",
  
  "epsbasic": "epsbasic",
  "eps basic": "epsbasic",
  "базовый eps": "epsbasic",
  "базовая прибыль на акцию": "epsbasic",
  "eps ba": "epsbasic",
  "earnings per share basic": "epsbasic",
  
  "epsdiluted": "epsdiluted",
  "eps diluted": "epsdiluted",
  "разводненный eps": "epsdiluted",
  "разводненная прибыль на акцию": "epsdiluted",
  "eps dil": "epsdiluted",
  "earnings per share diluted": "epsdiluted",
  
  "dividendspershare": "dividendspershare",
  "dps": "dividendspershare",
  "дивиденды на акцию": "dividendspershare",
  "dividends per share": "dividendspershare",
  "дивиденд на одну акцию": "dividendspershare",
  "пер акцию дивиденды": "dividendspershare"
};

// ============ 3. ДОПОЛНИТЕЛЬНЫЕ СПРАВОЧНИКИ ==========

// Типы отчетов SEC
const FORM_TYPES = {
  annual: ['10-K', '20-F', '40-F'],
  quarterly: ['10-Q', '6-K'],
  current: ['8-K'],
  proxy: ['DEF 14A', 'PRE 14A'],
  registration: ['S-1', 'F-1'],
  all: ['10-K', '10-Q', '8-K', '20-F', '40-F', '6-K', 'DEF 14A', 'PRE 14A', 'S-1', 'F-1']
};

// Таксономии XBRL
const TAXONOMIES = ['us-gaap', 'ifrs-full', 'srt'];

// Единицы измерения в XBRL
const UNIT_TYPES = ['USD', 'shares', 'pure'];

// ============ 4. ЭКСПОРТ ==========
module.exports = {
  METRICS_CATALOG,
  METRIC_ALIASES,
  FORM_TYPES,
  TAXONOMIES,
  UNIT_TYPES
};
